edition = "2021"
max_width = 110
# won't add \r\n on windows machines, better on diffs
newline_style = "Unix"
use_small_heuristics = "Max"
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
