[package]
name = "hvm-lang"
version = "0.1.0"
edition = "2021"

[lib]
name = "hvml"
path = "src/lib.rs"

[[bin]]
name = "hvml"
path = "src/main.rs"
required-features = ["cli"]

[profile.release]
lto = true

[features]
default = ["cli"]
cli = ["dep:clap"]

[dependencies]
# Later versions of the alpha contains bugs that changes the parser errors
chumsky = { version = "= 1.0.0-alpha.4", features = ["label"] }
clap = { version = "4.4.1", features = ["derive"], optional = true }
highlight_error = "0.1.1"
hvm-core = { git = "https://github.com/HigherOrderCO/hvm-core" }
indexmap = "2.2.3"
interner = "0.2.1"
itertools = "0.11.0"
logos = "0.14.0"
stacker = "0.1"

[dev-dependencies]
insta = "1.34.0"
stdext = "0.3.1"
walkdir = "2.3.3"

[profile.test]
opt-level = 2
